import type { BusinessType } from '../../types/tenant'
import type { CustomFieldSeed } from '../../types/pipeline'

/**
 * Pre-configured custom field definitions per industry.
 * Used at onboarding to seed the custom_fields table for a new tenant.
 *
 * Rules:
 * - field_key values must be unique within an industry (enforced by DB unique constraint)
 * - Insertion uses ON CONFLICT DO NOTHING — existing fields are never overwritten
 * - show_in_list: only the most important 1-2 fields per industry
 * - show_in_card: all fields default to true (visible on lead detail page)
 */
export const CUSTOM_FIELD_SEEDS: Record<BusinessType, CustomFieldSeed[]> = {

  // ─── Real Estate ───────────────────────────────────────────────────────────
  real_estate: [
    {
      field_key:    'property_type',
      field_label:  'Property type',
      field_type:   'select',
      options:      ['Apartment', 'Villa', 'Plot', 'Commercial', 'Penthouse', 'Row House'],
      required:     false,
      sort_order:   1,
      show_in_list: true,
      show_in_card: true,
      placeholder:  undefined,
    },
    {
      field_key:    'bhk',
      field_label:  'BHK / Config',
      field_type:   'select',
      options:      ['1 BHK', '2 BHK', '3 BHK', '4 BHK', '4+ BHK', 'Studio'],
      required:     false,
      sort_order:   2,
      show_in_list: true,
      show_in_card: true,
    },
    {
      field_key:    'budget',
      field_label:  'Budget',
      field_type:   'currency',
      required:     false,
      sort_order:   3,
      show_in_list: false,
      show_in_card: true,
      placeholder:  '0.00',
    },
    {
      field_key:    'preferred_location',
      field_label:  'Preferred location',
      field_type:   'text',
      required:     false,
      sort_order:   4,
      show_in_list: false,
      show_in_card: true,
      placeholder:  'e.g. Bandra, Whitefield',
    },
    {
      field_key:    'possession_date',
      field_label:  'Possession date',
      field_type:   'date',
      required:     false,
      sort_order:   5,
      show_in_list: false,
      show_in_card: true,
    },
    {
      field_key:    'loan_required',
      field_label:  'Loan required',
      field_type:   'boolean',
      required:     false,
      sort_order:   6,
      show_in_list: false,
      show_in_card: true,
    },
  ],

  // ─── Insurance ────────────────────────────────────────────────────────────
  insurance: [
    {
      field_key:    'policy_type',
      field_label:  'Policy type',
      field_type:   'select',
      options:      ['Health', 'Life', 'Motor', 'Home', 'Travel', 'Business', 'Term'],
      required:     false,
      sort_order:   1,
      show_in_list: true,
      show_in_card: true,
    },
    {
      field_key:    'sum_insured',
      field_label:  'Sum insured',
      field_type:   'currency',
      required:     false,
      sort_order:   2,
      show_in_list: false,
      show_in_card: true,
      placeholder:  '0.00',
    },
    {
      field_key:    'premium_amount',
      field_label:  'Premium amount',
      field_type:   'currency',
      required:     false,
      sort_order:   3,
      show_in_list: false,
      show_in_card: true,
      placeholder:  '0.00',
    },
    {
      field_key:    'policy_number',
      field_label:  'Policy number',
      field_type:   'text',
      required:     false,
      sort_order:   4,
      show_in_list: false,
      show_in_card: true,
      placeholder:  'e.g. POL-2024-001',
    },
    {
      field_key:    'policy_start_date',
      field_label:  'Policy start date',
      field_type:   'date',
      required:     false,
      sort_order:   5,
      show_in_list: false,
      show_in_card: true,
    },
    {
      field_key:    'policy_expiry_date',
      field_label:  'Policy expiry date',
      field_type:   'date',
      required:     false,
      sort_order:   6,
      show_in_list: true,
      show_in_card: true,
    },
    {
      field_key:    'policy_status',
      field_label:  'Policy status',
      field_type:   'select',
      options:      ['New Lead', 'Quote Sent', 'Policy Issued', 'Renewal Due', 'Renewed', 'Lapsed'],
      required:     false,
      sort_order:   7,
      show_in_list: true,
      show_in_card: true,
    },
    {
      field_key:    'payment_frequency',
      field_label:  'Payment frequency',
      field_type:   'select',
      options:      ['Monthly', 'Quarterly', 'Half-Yearly', 'Annually'],
      required:     false,
      sort_order:   8,
      show_in_list: false,
      show_in_card: true,
    },
    {
      field_key:    'next_premium_due',
      field_label:  'Next premium due',
      field_type:   'date',
      required:     false,
      sort_order:   9,
      show_in_list: false,
      show_in_card: true,
    },
    {
      field_key:    'nominee_name',
      field_label:  'Nominee name',
      field_type:   'text',
      required:     false,
      sort_order:   10,
      show_in_list: false,
      show_in_card: true,
      placeholder:  'Nominee full name',
    },
    {
      field_key:    'assigned_agent_name',
      field_label:  'Assigned agent',
      field_type:   'text',
      required:     false,
      sort_order:   11,
      show_in_list: false,
      show_in_card: true,
      placeholder:  'Agent name',
    },
  ],

  // ─── Travel Agency ────────────────────────────────────────────────────────
  travel: [
    {
      field_key:    'destination',
      field_label:  'Destination',
      field_type:   'text',
      required:     false,
      sort_order:   1,
      show_in_list: true,
      show_in_card: true,
      placeholder:  'e.g. Bali, Dubai, Europe',
    },
    {
      field_key:    'departure_date',
      field_label:  'Departure date',
      field_type:   'date',
      required:     false,
      sort_order:   2,
      show_in_list: true,
      show_in_card: true,
    },
    {
      field_key:    'return_date',
      field_label:  'Return date',
      field_type:   'date',
      required:     false,
      sort_order:   3,
      show_in_list: false,
      show_in_card: true,
    },
    {
      field_key:    'passengers',
      field_label:  'Number of passengers',
      field_type:   'number',
      required:     false,
      sort_order:   4,
      show_in_list: false,
      show_in_card: true,
      placeholder:  '1',
    },
    {
      field_key:    'package_type',
      field_label:  'Package type',
      field_type:   'select',
      options:      ['Honeymoon', 'Family', 'Solo', 'Group Tour', 'Corporate', 'Adventure'],
      required:     false,
      sort_order:   5,
      show_in_list: false,
      show_in_card: true,
    },
    {
      field_key:    'visa_required',
      field_label:  'Visa required',
      field_type:   'boolean',
      required:     false,
      sort_order:   6,
      show_in_list: false,
      show_in_card: true,
    },
    {
      field_key:    'budget',
      field_label:  'Budget',
      field_type:   'currency',
      required:     false,
      sort_order:   7,
      show_in_list: false,
      show_in_card: true,
      placeholder:  '0.00',
    },
  ],

  // ─── Tarot / Astrology ────────────────────────────────────────────────────
  tarot: [
    {
      field_key:    'session_type',
      field_label:  'Session type',
      field_type:   'select',
      options:      ['Tarot Reading', 'Astrology Chart', 'Numerology', 'Healing Session', 'Vastu', 'Palmistry'],
      required:     false,
      sort_order:   1,
      show_in_list: true,
      show_in_card: true,
    },
    {
      field_key:    'birth_date',
      field_label:  'Date of birth',
      field_type:   'date',
      required:     false,
      sort_order:   2,
      show_in_list: false,
      show_in_card: true,
    },
    {
      field_key:    'birth_time',
      field_label:  'Time of birth',
      field_type:   'text',
      required:     false,
      sort_order:   3,
      show_in_list: false,
      show_in_card: true,
      placeholder:  'e.g. 10:30 AM',
    },
    {
      field_key:    'birth_place',
      field_label:  'Place of birth',
      field_type:   'text',
      required:     false,
      sort_order:   4,
      show_in_list: false,
      show_in_card: true,
      placeholder:  'e.g. Mumbai, Maharashtra',
    },
    {
      field_key:    'session_duration',
      field_label:  'Session duration',
      field_type:   'select',
      options:      ['30 min', '45 min', '60 min', '90 min'],
      required:     false,
      sort_order:   5,
      show_in_list: false,
      show_in_card: true,
    },
    {
      field_key:    'session_fee',
      field_label:  'Session fee',
      field_type:   'currency',
      required:     false,
      sort_order:   6,
      show_in_list: false,
      show_in_card: true,
      placeholder:  '0.00',
    },
  ],

  // ─── Coaching ─────────────────────────────────────────────────────────────
  coach: [
    {
      field_key:    'coaching_type',
      field_label:  'Coaching type',
      field_type:   'select',
      options:      ['Business', 'Life', 'Career', 'Fitness', 'Relationship', 'Executive', 'NLP'],
      required:     false,
      sort_order:   1,
      show_in_list: true,
      show_in_card: true,
    },
    {
      field_key:    'sessions_booked',
      field_label:  'Sessions booked',
      field_type:   'number',
      required:     false,
      sort_order:   2,
      show_in_list: false,
      show_in_card: true,
      placeholder:  '0',
    },
    {
      field_key:    'sessions_completed',
      field_label:  'Sessions completed',
      field_type:   'number',
      required:     false,
      sort_order:   3,
      show_in_list: false,
      show_in_card: true,
      placeholder:  '0',
    },
    {
      field_key:    'monthly_fee',
      field_label:  'Monthly fee',
      field_type:   'currency',
      required:     false,
      sort_order:   4,
      show_in_list: false,
      show_in_card: true,
      placeholder:  '0.00',
    },
    {
      field_key:    'start_date',
      field_label:  'Start date',
      field_type:   'date',
      required:     false,
      sort_order:   5,
      show_in_list: false,
      show_in_card: true,
    },
    {
      field_key:    'goal',
      field_label:  'Client goal',
      field_type:   'textarea',
      required:     false,
      sort_order:   6,
      show_in_list: false,
      show_in_card: true,
      placeholder:  'What does the client want to achieve?',
    },
  ],

  // ─── Education ────────────────────────────────────────────────────────────
  education: [
    {
      field_key:    'course',
      field_label:  'Course interested in',
      field_type:   'text',
      required:     false,
      sort_order:   1,
      show_in_list: true,
      show_in_card: true,
      placeholder:  'e.g. MBA, Data Science, CA',
    },
    {
      field_key:    'academic_background',
      field_label:  'Academic background',
      field_type:   'text',
      required:     false,
      sort_order:   2,
      show_in_list: false,
      show_in_card: true,
      placeholder:  'e.g. 12th Science, B.Com',
    },
    {
      field_key:    'fee_quoted',
      field_label:  'Fee quoted',
      field_type:   'currency',
      required:     false,
      sort_order:   3,
      show_in_list: false,
      show_in_card: true,
      placeholder:  '0.00',
    },
    {
      field_key:    'fee_paid',
      field_label:  'Fee paid',
      field_type:   'currency',
      required:     false,
      sort_order:   4,
      show_in_list: false,
      show_in_card: true,
      placeholder:  '0.00',
    },
    {
      field_key:    'enrollment_number',
      field_label:  'Enrollment number',
      field_type:   'text',
      required:     false,
      sort_order:   5,
      show_in_list: false,
      show_in_card: true,
      placeholder:  'Filled after enrollment',
    },
    {
      field_key:    'batch',
      field_label:  'Batch / Class',
      field_type:   'text',
      required:     false,
      sort_order:   6,
      show_in_list: true,
      show_in_card: true,
      placeholder:  'e.g. Batch 2024-A',
    },
    {
      field_key:    'enrollment_status',
      field_label:  'Enrollment status',
      field_type:   'select',
      options:      ['Inquiry', 'Counselling', 'Demo Scheduled', 'Demo Done', 'Enrolled', 'Dropped Out'],
      required:     false,
      sort_order:   7,
      show_in_list: true,
      show_in_card: true,
    },
    {
      field_key:    'payment_mode',
      field_label:  'Payment mode',
      field_type:   'select',
      options:      ['Cash', 'Online', 'Cheque', 'EMI', 'Scholarship'],
      required:     false,
      sort_order:   8,
      show_in_list: false,
      show_in_card: true,
    },
    {
      field_key:    'admission_date',
      field_label:  'Admission date',
      field_type:   'date',
      required:     false,
      sort_order:   9,
      show_in_list: false,
      show_in_card: true,
    },
    {
      field_key:    'parent_name',
      field_label:  'Parent / Guardian name',
      field_type:   'text',
      required:     false,
      sort_order:   10,
      show_in_list: false,
      show_in_card: true,
      placeholder:  'Parent full name',
    },
    {
      field_key:    'parent_phone',
      field_label:  'Parent phone',
      field_type:   'text',
      required:     false,
      sort_order:   11,
      show_in_list: false,
      show_in_card: true,
      placeholder:  '+91 98765 43210',
    },
  ],

  // ─── Taxi / Transport ─────────────────────────────────────────────────────
  taxi: [
    {
      field_key:    'pickup_location',
      field_label:  'Pickup location',
      field_type:   'text',
      required:     false,
      sort_order:   1,
      show_in_list: true,
      show_in_card: true,
      placeholder:  'e.g. Airport T2, Hotel name',
    },
    {
      field_key:    'drop_location',
      field_label:  'Drop location',
      field_type:   'text',
      required:     false,
      sort_order:   2,
      show_in_list: true,
      show_in_card: true,
      placeholder:  'e.g. Churchgate Station',
    },
    {
      field_key:    'pickup_datetime',
      field_label:  'Pickup date & time',
      field_type:   'datetime',
      required:     false,
      sort_order:   3,
      show_in_list: false,
      show_in_card: true,
    },
    {
      field_key:    'vehicle_type',
      field_label:  'Vehicle type',
      field_type:   'select',
      options:      ['Sedan', 'SUV', 'Hatchback', 'Mini-bus', 'Bus', 'Tempo Traveller'],
      required:     false,
      sort_order:   4,
      show_in_list: false,
      show_in_card: true,
    },
    {
      field_key:    'passengers',
      field_label:  'Number of passengers',
      field_type:   'number',
      required:     false,
      sort_order:   5,
      show_in_list: false,
      show_in_card: true,
      placeholder:  '1',
    },
    {
      field_key:    'fare',
      field_label:  'Agreed fare',
      field_type:   'currency',
      required:     false,
      sort_order:   6,
      show_in_list: false,
      show_in_card: true,
      placeholder:  '0.00',
    },
    {
      field_key:    'recurring',
      field_label:  'Recurring booking',
      field_type:   'boolean',
      required:     false,
      sort_order:   7,
      show_in_list: false,
      show_in_card: true,
    },
    {
      field_key:    'trip_status',
      field_label:  'Trip status',
      field_type:   'select',
      options:      ['Pending', 'Assigned', 'In Transit', 'Completed', 'Cancelled'],
      required:     false,
      sort_order:   8,
      show_in_list: true,
      show_in_card: true,
    },
    {
      field_key:    'driver_name',
      field_label:  'Driver name',
      field_type:   'text',
      required:     false,
      sort_order:   9,
      show_in_list: false,
      show_in_card: true,
      placeholder:  'Assigned driver',
    },
    {
      field_key:    'driver_phone',
      field_label:  'Driver phone',
      field_type:   'text',
      required:     false,
      sort_order:   10,
      show_in_list: false,
      show_in_card: true,
      placeholder:  '+91 98765 43210',
    },
    {
      field_key:    'vehicle_number',
      field_label:  'Vehicle number',
      field_type:   'text',
      required:     false,
      sort_order:   11,
      show_in_list: false,
      show_in_card: true,
      placeholder:  'MH01AB1234',
    },
  ],

  // ─── Marketing Agency ─────────────────────────────────────────────────────
  marketing: [
    {
      field_key:    'campaign_type',
      field_label:  'Campaign type',
      field_type:   'multi_select',
      options:      ['SEO', 'Google Ads', 'Meta Ads', 'Email', 'Content', 'Social Media', 'Influencer', 'PR'],
      required:     false,
      sort_order:   1,
      show_in_list: true,
      show_in_card: true,
    },
    {
      field_key:    'monthly_budget',
      field_label:  'Monthly budget',
      field_type:   'currency',
      required:     false,
      sort_order:   2,
      show_in_list: true,
      show_in_card: true,
      placeholder:  '0.00',
    },
    {
      field_key:    'contract_start',
      field_label:  'Contract start date',
      field_type:   'date',
      required:     false,
      sort_order:   3,
      show_in_list: false,
      show_in_card: true,
    },
    {
      field_key:    'contract_end',
      field_label:  'Contract end date',
      field_type:   'date',
      required:     false,
      sort_order:   4,
      show_in_list: false,
      show_in_card: true,
    },
    {
      field_key:    'industry',
      field_label:  'Client industry',
      field_type:   'text',
      required:     false,
      sort_order:   5,
      show_in_list: false,
      show_in_card: true,
      placeholder:  'e.g. E-commerce, Healthcare',
    },
    {
      field_key:    'retainer',
      field_label:  'Retainer client',
      field_type:   'boolean',
      required:     false,
      sort_order:   6,
      show_in_list: false,
      show_in_card: true,
    },
    {
      field_key:    'contract_status',
      field_label:  'Contract status',
      field_type:   'select',
      options:      ['Prospect', 'Proposal Sent', 'Negotiating', 'Active', 'Paused', 'Cancelled', 'Completed'],
      required:     false,
      sort_order:   7,
      show_in_list: true,
      show_in_card: true,
    },
    {
      field_key:    'contract_value',
      field_label:  'Contract value',
      field_type:   'currency',
      required:     false,
      sort_order:   8,
      show_in_list: false,
      show_in_card: true,
      placeholder:  '0.00',
    },
    {
      field_key:    'revenue_to_date',
      field_label:  'Revenue to date',
      field_type:   'currency',
      required:     false,
      sort_order:   9,
      show_in_list: false,
      show_in_card: true,
      placeholder:  '0.00',
    },
    {
      field_key:    'account_manager',
      field_label:  'Account manager',
      field_type:   'text',
      required:     false,
      sort_order:   10,
      show_in_list: false,
      show_in_card: true,
      placeholder:  'Manager name',
    },
    {
      field_key:    'platforms_active',
      field_label:  'Active platforms',
      field_type:   'multi_select',
      options:      ['SEO', 'Google Ads', 'Meta Ads', 'Email', 'LinkedIn', 'YouTube', 'Instagram'],
      required:     false,
      sort_order:   11,
      show_in_list: false,
      show_in_card: true,
    },
  ],

  // ─── General Business ─────────────────────────────────────────────────────
  // Intentionally minimal — general businesses configure their own fields
  general: [
    {
      field_key:    'deal_value',
      field_label:  'Deal value',
      field_type:   'currency',
      required:     false,
      sort_order:   1,
      show_in_list: true,
      show_in_card: true,
      placeholder:  '0.00',
    },
    {
      field_key:    'priority',
      field_label:  'Priority',
      field_type:   'select',
      options:      ['Low', 'Medium', 'High', 'Urgent'],
      required:     false,
      sort_order:   2,
      show_in_list: true,
      show_in_card: true,
    },
  ],

  // ─── Custom — no pre-configured fields ────────────────────────────────────
  custom: [],
}
